NAME: 'aff_w10_graph_KD_T2_S2_node0.1_edge0.1_CIaff1_CInode0_CIedge1_MSE_MSE32_CS12_v7_3w_v2_test'
MODEL_T:
    model_type: 2
    input_nc: 3
    output_nc: 2
    if_sigmoid: True
    filters:
        - 32
        - 64
        - 179
        - 349
        - 680
    finetuning: False
    emd: 16


MODEL:
    model_type: 2
    input_nc: 3
    output_nc: 2
    if_sigmoid: True
    filters: 
        - 4
        - 8
        - 16
        - 32
        - 64
    finetuning: False
    emd: 16

TRAIN:
    resume: False
    if_valid: True
    if_seg: True
    if_KD: True
    if_neighbor: False
    model_T_id: 81000
    model_T_path: '/braindat/lab/liuxy/affinity_subnet/CVPPP/baseline_all_cos/models/2022-01-01--07-38-20_baseline_emb16_mutexT2_mse'
    cache_path: '../caches_extension/'
    save_path: '../models_extension/'
    loss_func: 'WeightedMSELoss'   # 'WeightedBCELoss', 'BCELoss'
    mask_weight: 0.0
    dis_weight: 1.0
    affinity_weight: 10
    node_weight: 0.1
    edge_weight: 0.1
    graph_node_mutual_weight: 200.0
    if_edge_relation: True
    if_edge_discrepancy: False
    if_node: True
    align_node_weight: 0.05
    align_edge_weight: 0.5
    align_structure_weight: 0.5
    memory_size: 32
    contrast_size: 12
    cikd_loss_type: 'MSE' #KL,MSE
    CI_affinity_weight: 1
    CI_graph_node_mutual_weight: 100.0
    CI_node_weight: 0
    CI_edge_weight: 1
    opt_type: 'adam'
    lr_mode: 'fixed'
    step_size: 50000
    gamma: 0.5
    total_iters: 300000
    warmup_iters: 0
    base_lr: 0.0001
    end_lr: 0.0001
    display_freq: 100
    show_freq: 1000
    valid_freq: 1000
    save_freq: 1000
    decay_iters: 100000
    weight_decay: ~
    power: 1.5
    batch_size: 2
    num_workers: 2
    if_cuda: True
    random_seed: 555  # -1 is none

DATA:
    dataset_name: 'A1'
    valid_set: 'local_20_1'
    remove_training_set: ~
    size: 544
    num_train: 108
    data_folder: '../data/A1'
    padding: True
    separate_weight: False
    background: False
    shifts:
        - 1
        - 3
        - 5
        - 9
        - 27
    neighbor: 4
    strides: 
        - 5
        - 5
    if_dilate: True
    widen_way: True
    if_scale_aug: True
    if_filp_aug: True
    if_rotation_aug: True
    if_intensity_aug: True
    if_elastic_aug: True
    aug_np: False

TEST:
    pad: 0
    model_name: ''
    if_mutex: True